name: Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  npm-publish:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: yarn changeset version
      - run: git config --global user.email "github-actions[bot]"
      - run: git config --global user.name github-actions[bot]@users.noreply.github.com
      - run: git commit -am "Bumped package versions 📦" || echo "Versions not updated. Nothing to commit."
        shell: bash {0} # opt-out of exit on error
      - run: git push
      - run: git push --follow-tags
      - run: yarn dlx publish-if-not-published
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

